### ISSUE TITLE
Add crwbok in the list

### ISSUE THREAD

**Issue by ngaumont** [writing-resources/awesome-scientific-writing#1]
Hi,

I find this list very useful and I think crowbook might be included in it : https://github.com/lise-henry/crowbook

However I've not tested it and specially how to seamlessly cite references part.

Noé

**Comment by ashwinvis** [comment]
Interesting! What about the other features: latex equations, and ability to reference internal figures and sections? I tried to figure out myself, but the documentation on usage is missing. Also, the line in their README is a bit unclear:

> Crowbook tries to correctly translate local links in the input Markdown files: e.g. if you have a link to a Markdown file that is part of your book, it will be transformed into a link inside the document.

It would be nice if you can have a quick test run. Pull requests are welcome by the way :)

**Comment by maehr** [comment]
Crowbook depends on LaTeX to produce PDF and has a lot of untested features that are required for scientific writing. I cannot see at the moment why this tool should belong in this list.
