### ISSUE TITLE
Migrate the awesome list to an organization

### ISSUE THREAD

**Issue by ashwinvis** [writing-resources/awesome-scientific-writing#14]
To merge with @maehr 's list: https://github.com/maehr/awesome-academic-writing

Suitable names for the org can be mentioned on comments below, and then we can vote with a :+1:  until say 24/3. The migration will be done on 25/3

See also: https://github.com/sindresorhus/awesome/pull/1700

**Comment by maehr** [comment]
awesome-academic-writing

**Comment by maehr** [comment]
awesome-scientific-writing

**Comment by ashwinvis** [comment]
writing-resources

**Comment by ashwinvis** [comment]
modern-writing

**Comment by ashwinvis** [comment]
sciwriting

**Comment by maehr** [comment]
> writing-resources

Do we have a winner?

**Comment by ashwinvis** [comment]
Yep.... will do it right away.

**Comment by ashwinvis** [comment]
Done. The website is now available at https://writing-resources.github.io/awesome-scientific-writing/
I will start a new issue for deciding how to merge.
