### ISSUE TITLE
Add jupyter-book

### ISSUE THREAD

**Issue by ashwinvis** [writing-resources/awesome-scientific-writing#19]
Enhancement of bookdown tool. Interactive online books. Jupyter + Jekyll

https://github.com/jupyter/jupyter-book

**Comment by ashwinvis** [comment]
The project has moved to a new home: 

https://github.com/executablebooks/jupyter-book

The flavour of markdown being used is called [MyST](https://myst-parser.readthedocs.io/en/latest/index.html)

**Comment by maehr** [comment]
Jupyter-book just made a big leap forward (and ditched jekyll) https://blog.jupyter.org/announcing-the-new-jupyter-book-cbf7aa8bc72e

**Comment by ashwinvis** [comment]
On one hand, I feel it is about time we should include jupyter-book here. I heard it mentioned several times in the past months and it has started to get adopted by users to write content: [like this](champsproject.github.io/lagrangian_descriptors/docs/authors.html). On the other hand I am unsure how it achieves anything that Sphinx (or equivalent documentation generator) would allow you to do with some extensions and a good template.

**Comment by maehr** [comment]
Since I do not work with notebooks but with plain Markdown, I cannot give a competent assessment. I know that it is based on Sphinx and already has a template and the right extensions.
