### ISSUE TITLE
ConTeXt as an alternative for intermediate output instead of LaTeX?

### ISSUE THREAD

**Issue by ashwinvis** [writing-resources/awesome-scientific-writing#2]
Considerations:
* Compatibilty with LaTeX templates
* Pandoc support
* Availabilty of ConTeXt compilers in university machines and ease of installation if absent

Recommendation from @denubis
> 
> Take a look at https://github.com/hmenke/context-examples/blob/master/GUIDE.md
> 
> My dissertation (finished 2012) is: https://github.com/Denubis/AskingAboutData
> 
> And a colleague's more recent: https://github.com/petrajanouchova/dis_context

**Comment by maehr** [comment]
I admire Hans Hagens work, but Context is basically a one man show. The lack of a dev community is a problem and I advice against integrating Context.

**Comment by ashwinvis** [comment]
I see. I had my doubts because of the verbose syntax. It does not fit in this awesome list then. Closing it for now.
