### ISSUE TITLE
Add to main awesome list

### ISSUE THREAD

**Issue by ashwinvis** [writing-resources/awesome-scientific-writing#20]
i.e. https://github.com/sindresorhus/awesome
Here is a copypasta of the and old version of the [checklist](https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md), but I think most of the tasks are still valid.

> I have read and understood the contribution guidelines and the instructions for creating a list.
 - [x] This pull request has a descriptive title.
 - [x] For example, Add Name of List, not Update readme.md or Add awesome list.
 - [x] The entry in the Awesome list should:
	 - [x]     Include a short description about the list project/theme. It should not describe the list itself.
	 - [x]     Example: - [Fish](…) - User-friendly shell.
	 - [x]     Be added at the bottom of the appropriate category.
  - [ ] The list I'm submitting complies with these requirements:
	 - [x]     Has been around for at least 30 days.
	 - [x]     That means 30 days from either the first real commit or when it was open-sourced. Whatever is most recent.
	 - [x]     It's the result of hard work and the best I could possibly produce.
	 - [x]     Non-generated Markdown file in a GitHub repo.
	 - [x]     The repo should have the following GitHub topics set: awesome-list, awesome, list. I encourage you to add more relevant topics.
	 - [x]     Not a duplicate.
	 - [x]     Includes a succinct description of the project/theme at the top of the readme. (Example)
	 - [x]     Only has awesome items. Awesome lists are curations of the best, not everything.
	 - [ ]     Includes a project logo/illustration whenever possible.
		 - [ ]         Placed at the top-right of the readme. (Example)
		 - [ ]         The image should link to the project website or any relevant website.
		 - [ ]         The image should be high-DPI. Set it to maximum half the width of the original image.
	 - [x]     Entries have a description, unless the title is descriptive enough by itself. It rarely is though.
	 - [x]     Has the Awesome badge on the right side of the list heading,
	 - [x]     Has a Table of Contents section.
		 - [x]         Should be named Contents, not Table of Contents.
		 - [x]         Should be the first section in the list.
	 - [x]     Has an appropriate license.
		 - [x]         That means something like CC0, not a code licence like MIT, BSD, Apache, etc.
		 - [x]         If you use a license badge, it should be SVG, not PNG.
	 - [x]     Has contribution guidelines.
		 - [x]         The file should be named contributing.md. Casing is up to you.
	 - [x]     Has consistent formatting and proper spelling/grammar.
		 - [x]         Each link description starts with an uppercase character and ends with a period.
		 - [x]         Example: - [AVA](…) - JavaScript test runner.
		 - [x]         Drop all the A / An prefixes in the descriptions.
		 - [x]         Consistent naming. For example, Node.js, not NodeJS or node.js.
	 - [x]     Doesn't include a Travis badge. You can still use Travis for list linting, but the badge has no value in the readme.
- [x] Go to the top and read it again.

**Comment by maehr** [comment]
@ashwinvis I think that - apart from these minor changes - we are ready to go:

- Logo is missing (I am a big fan of the https://openmoji.org/ project, but I don't really care what logo we use.)
- Drop the "A" in the list, see https://github.com/writing-resources/awesome-scientific-writing/pull/25

Do you want me to open a PR to https://github.com/sindresorhus/awesome/

**Comment by ashwinvis** [comment]
We can use the logo you suggested :). And feel free to submit a PR - I cannot do it because I have not done any "peer review" in the awesome repo.

**Comment by maehr** [comment]
@ashwinvis I changed https://github.com/sindresorhus/awesome/pull/1700 accordingly

**Comment by ashwinvis** [comment]
@maehr this
> To verify that you've read all the guidelines, please comment on your pull request with just the word unicorn.

**Comment by maehr** [comment]
> @maehr this
> 
> > To verify that you've read all the guidelines, please comment on your pull request with just the word unicorn.

Unfortunately, nothing is happening...

**Comment by ashwinvis** [comment]
@maehr I poked the maintainer to reply what's missing. So I got this:

> I see Markdown being written as markdown in at least one of the descriptions.

Done in #30 

> I also see some typos in the descriptions.

Done with some help from hunspell #30

> Please go through all the descriptions and try to improve them.

That's kind of vague, IMHO :man_shrugging:

**Comment by maehr** [comment]
@ashwinvis Thanks for your work. I also don't know what is meant by improving all descriptions. Let's try again with our pull request and see what happens.

**Comment by ashwinvis** [comment]
Completed with sindresorhus/awesome/pull/1798
