### ISSUE TITLE
Add MyST

### ISSUE THREAD

**Issue by maehr** [writing-resources/awesome-scientific-writing#29]
Add https://myst-parser.readthedocs.io/en/latest/ to converters.

@ashwinvis Could also be used to replace RSt in our list altogether ;)

**Comment by ashwinvis** [comment]
I have a bittersweet relation with rST. It is more standardised, and extendable than markdown, but it can throw a lot of errors too.

Also related to #19, which is the frontend for MyST. Have you tried it?

**Comment by maehr** [comment]
I am currently converting the docs of an older repo to md and expose it via sphinx. Seems to work pretty well.
https://myst-parser.readthedocs.io/en/latest/api/sphinx_parser.html
