### ISSUE TITLE
Change master to main

### ISSUE THREAD

**Issue by maehr** [writing-resources/awesome-scientific-writing#31]
According to the new guidelines of awesome list we need to change the name of the default branch. See https://github.com/sindresorhus/awesome/pull/1798#issuecomment-644338164

**Comment by maehr** [comment]
I am very sorry for opening this issue. I fail to find this requirement in the new guidelines.

**Comment by ashwinvis** [comment]
Since, it is a small project and a small change - if it makes people more comfortable, we can do it.

**Comment by ashwinvis** [comment]
Done!
