### ISSUE TITLE
Update contributing guidelines

### ISSUE THREAD

**Issue by ashwinvis** [writing-resources/awesome-scientific-writing#33]
And pull request template

Criteria:
- Number of entries per PR
- What kind of entries are welcome in this list.
- Only open-source stuff / free as in beer stuff too?

**Comment by maehr** [comment]
For me the most important issue is to keep the spirit of awesome lists alive. It's not about having all available tools listed, but the best tools. Therefore I want people to share their experience with the (one) tool they propose. And I would like to focus on OSS.

**Comment by ashwinvis** [comment]
I agree. +1 on limiting to F/OSS - that allows us to look at repo statistics to find out if it is truly awesome or not.

**Comment by ashwinvis** [comment]
Also, we should limit the PR to one entry if it is a new addition.
