### ISSUE TITLE
Awesome git (+ rstudio) tutorial

### ISSUE THREAD

**Issue by maehr** [writing-resources/awesome-scientific-writing#37]
I'm not 100% sure if this fits into our list, but it's definitely a great guide.
https://happygitwithr.com/

**Comment by ashwinvis** [comment]
Majority of the content is about setting up git and rstudio. Version control is really useful for serious scientific writing. If it is useful for users of RStudio, I have no strong objections against adding it as a tutorial.

**Comment by maehr** [comment]
I withdraw my proposal. We should keep the list as slim as possible.
