### ISSUE TITLE
404 GitHub page

### ISSUE THREAD

**Issue by maehr** [writing-resources/awesome-scientific-writing#39]
@ashwinvis I get an 404 on https://writing-resources.github.io/awesome-scientific-writing/

Do you experience the same behavior?

**Comment by ashwinvis** [comment]
I get that too... Strange!

**Comment by ashwinvis** [comment]
>  GitHub Pages is currently disabled. Select a source below to enable GitHub Pages for this repository. Learn more. 

Apparently gh-pages got disabled when we switched from master to main.

**Comment by ashwinvis** [comment]
Fixed. Thanks for reporting!
