### ISSUE TITLE
asciidoc and asciidoctor

### ISSUE THREAD

**Issue by ashwinvis** [writing-resources/awesome-scientific-writing#4]
Converter http://asciidoctor.org/ which is the reference implementation of [asciidoc](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/).

# Considerations
* LaTeX template support
* BibTeX support
* Incomplete pandoc support (see https://github.com/jgm/pandoc/issues/1456), in case asciidoctor does not function as intended

Recommended by @profoundlynerdy@mastodon.technology

**Comment by ashwinvis** [comment]
From the [docs](https://asciidoctor.org/docs/asciidoc-vs-markdown/#getting-your-start-with-markdown)

> Here’s how the story inevitably goes. You start out with Markdown. Then it’s Markdown + X. Then Markdown + X + Y. And down the rabbit hole you go. What’s worse, X and Y often require you to sprinkle in HTML, unnecessarily coupling content with presentation and wrecking portability. Your instinct to choose Markdown is good. There are just better options.

I agree! Common Markdown is not good enough.

## Features

The [quick reference](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#bibliography) guide shows native support for:

* [Bibliography](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#bibliography)
* [Links and cross-references](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/#links)

and the [user manual](https://asciidoctor.org/docs/user-manual/#stem):

* [MathJax, MathML and a stem attribute](https://asciidoctor.org/docs/user-manual/#stem)

There are also [alternative processors](https://github.com/asciidoctor/asciidoctor/issues/3575) for math.

## Conversion

Conversion to PDF and LaTeX requires plugins:
* https://github.com/asciidoctor/asciidoctor-pdf
* https://github.com/asciidoctor/asciidoctor-latex

## Interesting issues
* https://github.com/asciidoctor/asciidoctor/issues/3579
* https://github.com/asciidoctor/asciidoctor/issues/3575

**Comment by ashwinvis** [comment]
I think asciidoctor deserves to be added in the list!

**Comment by maehr** [comment]
I advice against it, as Latex support is stale https://github.com/asciidoctor/asciidoctor-latex and official documentation is down. https://asciidoctor.org/docs/#supplemental-converters links to 
http://www.noteshare.io/section/asciidoctor-latex-manual-intro
